### ISSUE TITLE
Region Data Enhancement

### ISSUE THREAD

**Issue by danreale** [danreale/transplant#1]
I'd like to change the UI experience on this page. https://heart-transplant.netlify.app/today?waitListType=All+Types

to something that looks like this structurally.

https://excalidraw.com/#json=A5QVueZ0oysmh9piWGuo2,FF4eDrqpWgv29D-_P8L1_A

Please design the shit out of this and make it as nice as you want. Use your own ideas and judgements during design. The goal is to provide a clean, modern look that is better than the boring look now.  I was thinking of a dashboard like feel when thinking about how to redesign this. So maybe keep that in mind. If it had a dashboard like feel, that would be cool.

Requirements:

- This needs to be reactive. Needs to work on mobile and web. It would be great if this could look similar to the row it is now. I know sometimes on mobile, the row changes to grid. I'd like to avoid that if possible for the region stats boxes. We use mobile much more than on the web, so mobile matters much more for people sitting in the hospital on their phones.
- Add info icon/button that when pressed, will show a popover of the Region states. clicking anywhere off the popover closes it.
- Add "View Trends" link that points to `/chart/{region_number}`
- Add trend line. If diff is negative, point down and color green. If diff is positive, point up and color red. Change number should be same color as trend line. If no change (0) then color yellow.
- Total number - color grey
- Region 2 title should be red. (region son is in that we really care about)
- Region 1,3,9,10,11 blue (Other regions he could accept from that we want to easily look at when coming to the site. Something to catch our attention)
- Update component on routes: `/today`, '/yesterday`
- If you have any other ideas and suggestions for making the page look more modern, cleaner, more well rounded, more user friendly, just do it.
- If might be cool if we could take this component and open source it. What do you think?

**Comment by paineleffler** [comment]
perfect, yeah this is good direction for me to start. i think a cool future enhancement could be star-ing certain regions and having those favorite regions appear at the top. we could even rely on session or local storage so that we don't have to build crazy backend features to support that

**Comment by danreale** [comment]
@paineleffler That's a cool idea about using session or local storage to have people select their favorites. I really like that. Since there's no concept of "users" or "accounts" for this app, in theory, those favorites will always be saved in local storage right?
